version: '3'
services:
  mysql-1:
    image: mysql:latest
    container_name: mysql-1
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: stockdb
      TZ: Asia/Seoul
    ports:
      - 3306:3306